name: Release

on:
  push:
    branches: [ "main", "release/*" ]
jobs:
  build:
    timeout-minutes: 10
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dotnet/nbgv@master
        id: nbgv
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
          dotnet-quality: 'ga'
      - name: Build and Test
        run: dotnet test -c Release
      - name: Pack JOS.Result ${{ steps.nbgv.outputs.nugetpackageversion }}
        run: dotnet pack src/JOS.Result/JOS.Result.csproj -c Release -o ./nuget-packages --no-build
      - name: Push version ${{ steps.nbgv.outputs.nugetpackageversion }} packages
        run: dotnet nuget push ./nuget-packages/** --source nuget.org --api-key ${{secrets.NUGET_API_KEY}}

