name: Release

on:
  push:
    branches: [ "main", "release/*" ]
jobs:
  build:
    timeout-minutes: 10
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dotnet/nbgv@master
        id: nbgv
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
          dotnet-quality: 'ga'
      - name: Build and Test
        run: dotnet test -c Release
      - name: Pack JOS.Result.sln ${{ steps.nbgv.outputs.nugetpackageversion }}
        run: dotnet pack JOS.Result.sln -c Release -o ./nuget-packages --no-build
      - name: Nuget - Login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Push version ${{ steps.nbgv.outputs.nugetpackageversion }} packages
        run: dotnet nuget push ./nuget-packages/** --skip-duplicate --source nuget.org --api-key ${{steps.login.outputs.NUGET_API_KEY}}

